erDiagram
    CLIENTE ||--o{ PROYECTO : "tiene"
    PROYECTO ||--o{ REQUERIMIENTO_DE_PROYECTO : "contiene"
    PROYECTO ||--o| PRESUPUESTO : "tiene"
    PRESUPUESTO ||--|{ DETALLE_PRESUPUESTO : "incluye"
    PROYECTO ||--o{ ASIGNACION_RECURSO : "asigna"
    PROYECTO ||--o{ SPRINT_DE_PROYECTO  : "define"
    PROYECTO }o--o{ COLABORADORES : "participa"

    CLIENTE {
        int id_cliente PK
        string email_cliente
        string empresa_cliente
        string rfc_cliente
    }

    PROYECTO {
        int id_cliente PK
        string nombre_proyecto
        string descripcion_proyecto
        string complejidad
        date fechaInicio_proyecto
        date fechaFin_proyecto
        string estado_proyecto
        int id_Cliente FK
    }

    REQUERIMIENTO_DE_PROYECTO {
        int id_requerimiento PK
        int id_Proyecto FK
        string descripcion
        string tipo_requerimiento
        string prioridad_requerimiento
        int horasEstimadas
    }

    PRESUPUESTO {
        int id PK
        int idProyecto FK
        decimal subtotal
        decimal iva
        decimal total
        date fechaElaboracion
        string estado
    }

    DETALLE_PRESUPUESTO {
        int id PK
        int idPresupuesto FK
        string concepto
        int cantidad
        decimal precioUnitario
        decimal subtotal
    }

    ASIGNACION_RECURSO {
        int id PK
        int idProyecto FK
        string rol
        int cantidad
        int horas
        decimal tarifaHora
    }

    SPRINT_DE_PROYECTO {
        int id PK
        int idProyecto FK
        string nombre
        date fechaInicio
        date fechaFin
        string estado_sprint
    }

    COLABORADORES {
        int id PK
        string nombre
        string email
        string rol
    }