erDiagram
    CLIENTE ||--o{ PROYECTO : "tiene"
    PROYECTO ||--|| PRESUPUESTOS_DE_PROYECTO : "tiene"
    PRESUPUESTOS_DE_PROYECTO ||--|{     DETALLES_DE_PRESUPUESTOS : "incluye"
    PROYECTO ||--o{ ASIGNACION_RECURSO : "asigna"
    PROYECTO ||--o{ SPRINTS_DE_PROYECTOS  : "define"
    PROYECTO ||--o{ REQUERIMIENTOS_DE_PROYECTO : "contiene"
    SPRINTS_DE_PROYECTOS ||--o{REQUERIMIENTOS_DE_PROYECTO : "implementan"
    SPRINTS_DE_PROYECTOS ||--o{COLABORADORES : "participan"
    PROYECTO }o--o{ COLABORADORES : "participan"




    CLIENTE {
        int id_cliente PK
        string email_cliente
        string empresa_cliente
        string rfc_cliente
    }

    PROYECTO {
        int id_proyecto PK
        int id_cliente_fk FK
        int id_presupuesto_fk FK
        string nombre_proyecto
        string descripcion_proyecto
        string complejidad_proyecto
        date fechaInicio_proyecto
        date fechaFin_proyecto
        string estado_proyecto
    }

    REQUERIMIENTOS_DE_PROYECTO {
        int id_requerimiento PK
        int id_proyecto_fk FK
        int id_sprint FK
        string descripcion_requerimiento
        string tipo_requerimiento
        string prioridad_requerimiento
        int horasEstimadas_requerimiento
    }

    PRESUPUESTOS_DE_PROYECTO {
        int id_presupuesto PK
        int id_proyecto_fk FK
        decimal total_presupuesto
        date fecha_elaboracion
        string estado_presupuesto
    }

    DETALLES_DE_PRESUPUESTOS {
        int id_detalle_presupuesto PK
        int id_presupuesto_fk FK
        string metodo_de_pago
        decimal precio
        decimal subtotal_detalle
        decimal iva_detalle
    }

    ASIGNACION_RECURSO {
        int id_asignacion PK
        int id_proyecto_fk FK
        int cantidad_asignacion
        int horas_asignacion
        decimal tarifaHora_asignacion
    }

    SPRINTS_DE_PROYECTOS {
        int id_sprint PK
        int id_proyecto_fk FK
        string nombre_sprint
        date fechaInicio_sprint
        date fechaFin_sprint
        string estado_sprint
    }

    COLABORADORES {
        int id_colaborador PK
        int id_proyecto_fk FK
        int id_sprint_fk FK
        string nombre_colaborador
        string email_colaborador
        string rol_colaborador
    }