erDiagram
    CLIENTE ||--o{ PROYECTO : "tiene"
    PROYECTO ||--o{ REQUERIMIENTOS_DE_PROYECTO : "contiene"
    PROYECTO ||--|| PRESUPUESTOS_DE_PROYECTO : "tiene"
    PRESUPUESTOS_DE_PROYECTO ||--|{ DETALLE_PRESUPUESTO : "incluye"
    PROYECTO ||--o{ ASIGNACION_RECURSO : "asigna"
    PROYECTO ||--o{ SPRINT_DE_PROYECTO  : "define"
    PROYECTO }o--o{ COLABORADORES : "participan"


    CLIENTE {
        int id_Cliente PK
        string email_cliente
        string empresa_cliente
        string rfc_cliente
    }

    PROYECTO {
        int id_Proyecto PK
        int id_Cliente FK
        string nombre_proyecto
        string descripcion_proyecto
        string complejidad_proyecto
        date fechaInicio_proyecto
        date fechaFin_proyecto
        string estado_proyecto
    }

    REQUERIMIENTOS_DE_PROYECTO {
        int id_Requerimiento PK
        int id_Proyecto FK
        string descripcion_requerimiento
        string tipo_requerimiento
        string prioridad_requerimiento
        int horasEstimadas_requerimiento
    }

    PRESUPUESTOS_DE_PROYECTO {
        int id_Presupuesto PK
        int id_Proyecto FK
        decimal subtotal
        decimal iva
        decimal total
        date fechaElaboracion
        string estado
    }

    DETALLE_PRESUPUESTO {
        int id_Presupuesto PK
        int id_Proyecto FK
        string concepto
        int cantidad
        decimal precioUnitario
        decimal subtotal
    }

    ASIGNACION_RECURSO {
        int id_Asignacion PK
        int id_Proyecto FK
        int cantidad
        int horas
        decimal tarifaHora
    }

    SPRINT_DE_PROYECTO {
        int id_Sprint PK
        int id_Proyecto FK
        string nombre
        date fechaInicio
        date fechaFin
        string estado_sprint
    }

    COLABORADORES {
        int id_Colaborador PK
        int id_Proyecto FK
        string nombre_colaborador
        string email_colaborador
        string rol_colaborador
    }